version: "3"

services:

  consul:
    image: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8500:8500
      - 8600:8600
    hostname: dev-consul
    container_name: dev-consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  datastore:
    image: mongo
    ports:
      - "27017"

  database:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  nats:
    image: nats
    ports:
      - 4222
      - 8222:8222

  
  consignment-service:
    image: shippy-service-consignment
    ports:
      - "50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"
      DB_HOST: "mongodb://datastore:27017"
      ENABLE_AUTH: ${ENABLE_AUTH}
    depends_on:
      - consul
      - datastore
      - vessel-service

  vessel-service:
    image: shippy-service-vessel
    ports:
      - "50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - consul
      - datastore

  user-service:
    image: shippy-service-user
    ports:
      - "50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - consul
      - database
      - nats

  email-service:
    image: shippy-service-email
    ports:
      - "50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
    depends_on:
      - consul
      - nats

  api:
    command: api --handler=rpc --namespace=shippy
    image: microhq/micro
    ports:
      - 8080:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"

  web:
    command: web
    image: microhq/micro
    ports:
      - 8082:8082
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "dev-consul"
